
package ua.artcode.service_country;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountriesPort", targetNamespace = "http://www.artcode.ua/service-country")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesPort {


    /**
     * 
     * @param getAllCountriesRequest
     * @return
     *     returns ua.artcode.service_country.GetAllCountriesResponse
     */
    @WebMethod
    @WebResult(name = "getAllCountriesResponse", targetNamespace = "http://www.artcode.ua/service-country", partName = "getAllCountriesResponse")
    public GetAllCountriesResponse getAllCountries(
        @WebParam(name = "getAllCountriesRequest", targetNamespace = "http://www.artcode.ua/service-country", partName = "getAllCountriesRequest")
        GetAllCountriesRequest getAllCountriesRequest);

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns ua.artcode.service_country.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://www.artcode.ua/service-country", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "http://www.artcode.ua/service-country", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

    /**
     * 
     * @param addCountryRequest
     * @return
     *     returns ua.artcode.service_country.AddCountryResponse
     */
    @WebMethod
    @WebResult(name = "addCountryResponse", targetNamespace = "http://www.artcode.ua/service-country", partName = "addCountryResponse")
    public AddCountryResponse addCountry(
        @WebParam(name = "addCountryRequest", targetNamespace = "http://www.artcode.ua/service-country", partName = "addCountryRequest")
        AddCountryRequest addCountryRequest);

}
